---
linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - paralleltest
    - cyclop
    - ireturn
    - wrapcheck
    - forcetypeassert
    - maligned
    - depguard
    - dupword
    - tagalign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

linters-settings:
  gocyclo:
    min-complexity: 40

  funlen:
    lines: 160
    statements: 60

  cyclop:
    max-complexity: 30

  lll:
    line-length: 165

  dupl:
    threshold: 450

run:
  concurrency: 10
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - scripts/
    - vendor/
    - docs/
  skip-files:
    - Makefile
    - README.md
    - Dockerfile

severity:
  default-severity: error

service:
  golangci-lint-version: 1.27.x
  prepare:
    - make local.check
