# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
        -X github.com/nikhilsbhat/yamll/cmd.Version={{.Version}}
        -X github.com/nikhilsbhat/yamll/cmd.Env={{.Env.BUILD_ENVIRONMENT}}
        -X github.com/nikhilsbhat/yamll/cmd.BuildDate={{.Date}}
        -X github.com/nikhilsbhat/yamll/cmd.Revision={{.Commit}}
        -X github.com/nikhilsbhat/yamll/cmd.GoVersion={{.Env.GOVERSION}}
        -X github.com/nikhilsbhat/yamll/cmd.Platform={{ .Os }}/{{ .Arch }}
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    binary: '{{ .ProjectName }}'

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - yamll
    skip_push: false
    image_templates:
      - "ghcr.io/nikhilsbhat/yamll:latest"
      - "ghcr.io/nikhilsbhat/yamll:{{ .Tag }}"
      - "ghcr.io/nikhilsbhat/yamll:{{ .Tag }}-{{ .Env.GOVERSION }}"
    dockerfile: Dockerfile

archives:
  - format: 'tar.gz'
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

snapshot:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}" # set this environment variable for your signing key
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
